/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domesticfinancesystem.inttrans;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JList;

/**
 *
 * @author sneha
 */
public class WalletComboBoxCellPanel extends javax.swing.JPanel {

    /**
     * Creates new form WalletComboBoxCellPanel
     */
    public WalletComboBoxCellPanel() {
        initComponents();
    }
    public void setRendererBackground(Color color)
    {
       super.setBackground(color);
       lblWalletName.setBackground(color);
       lblWalletAmt.setBackground(color);
    }
    public void setRendererForeground(Color color,boolean val)
    {
       super.setForeground(color);
       if(val)
       {
          lblWalletName.setForeground(color);
          lblWalletAmt.setForeground(color); 
       }
       else
       {
        lblWalletName.setForeground(new Color(0, 100, 0));
        lblWalletAmt.setForeground(new Color(0, 0, 100));
       }
       
    }
    public void setValue(WalletInfo obj,JList list)
    {
            if(obj!=null)
            {
               lblWalletName.setText(obj.getName());
               if(obj.isIsLiquid())
                 lblWalletAmt.setText(""+obj.getLiquidAmount());
               else
                 lblWalletAmt.setText(""+obj.getDigitalAmount());
               
               setRendererBackground(list.getBackground());
               setRendererForeground(list.getForeground(),false);
  
            }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWalletName = new javax.swing.JLabel();
        lblWalletAmt = new javax.swing.JLabel();

        lblWalletName.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        lblWalletName.setForeground(new java.awt.Color(0, 153, 51));
        lblWalletName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblWalletAmt.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblWalletAmt.setForeground(new java.awt.Color(0, 0, 153));
        lblWalletAmt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWalletName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblWalletAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWalletName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWalletAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblWalletAmt;
    private javax.swing.JLabel lblWalletName;
    // End of variables declaration//GEN-END:variables
}
