/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domesticfinancesystem.regularservice;

import java.awt.Color;
import java.awt.Window;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author sneha
 */
public class CalCellRenderer extends javax.swing.JPanel {

    /**
     * Creates new form CalendarCellRenderer
     */
    private int daynumber;
    private char satsun;
    private RegServ rs;
    private Date date;
    private int servDefId;
    private Color color;
    private MouseListener click;
    private boolean isDateValid;

    public boolean isIsDateValid() {
        return isDateValid;
    }
   public  void setValue(int num,Date dt,char ch,int servDefId,Color color,boolean isDateValid)//wll be implemented later
    {
        lblMiddle.setText(""+num);
        daynumber = num;
        satsun = ch;
        date = dt;
        this.servDefId = servDefId;
        this.isDateValid = isDateValid;
        this.color = color;
        
    }
   public void setBackgColor(Color color)
   {
       lblMiddle.setBackground(color);
   }
   
   public void resetBackgColor()
   {
       lblMiddle.setBackground(this.getBackground());
   }

    public RegServ getRs() {
        return rs;
    }

    public void setRs(RegServ rs) {
        this.rs = rs;
    }
   
    public char getSatSun()
    {
        return satsun;
    }
    
    public void setLabelsDisabled()
    {
        lblMiddle.setEnabled(false);
    }
    
     public void setLabelsEnabled()
    {
        lblMiddle.setEnabled(true);
    }
    
    public int getDaynumber()
    {
        return daynumber;
    }
    
    
    public void highlightLabel(Color color)
    {
        lblMiddle.setForeground(color);
        lblMiddle.setText(lblMiddle.getText());
    }
   
    public CalCellRenderer() {
        initComponents();
        
        click = new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent e)
            {
                if(servDefId != -1 && isDateValid == true)
                {
                    JFrame f = null;
                    JDialog dlg= new JDialog(f,true);
                    RegularServicePanel rsp = new RegularServicePanel(date, servDefId, dlg);
                    dlg.add(rsp);
                    dlg.pack();
                    dlg.setLocationRelativeTo(null);
                    dlg.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                    dlg.setVisible(true);

                    boolean saved = rsp.isServiceSaved();
                    if(saved)
                    {
                        setBackgColor(color);
                    }
                    else
                        resetBackgColor();
                }
        }

    };
      this.addMouseListener(click);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMiddle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        setMaximumSize(new java.awt.Dimension(95, 50));
        setPreferredSize(new java.awt.Dimension(95, 100));
        setLayout(new java.awt.BorderLayout());

        lblMiddle.setBackground(new java.awt.Color(255, 255, 255));
        lblMiddle.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        lblMiddle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMiddle.setText("23");
        lblMiddle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMiddle.setOpaque(true);
        add(lblMiddle, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMiddle;
    // End of variables declaration//GEN-END:variables
}
