/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domesticfinancesystem.regularservice;

import domesticfinancesystem.inttrans.*;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author sneha
 */
public class ItemComboBoxCellPanel extends javax.swing.JPanel {

    /**
     * Creates new form WalletComboBoxCellPanel
     */
    public ItemComboBoxCellPanel() {
        initComponents();
    }
    public void setRendererBackground(Color color)
    {
       super.setBackground(color);
       lblItemName.setBackground(color);
    }
    public void setRendererForeground(Color color)
    {
       super.setForeground(color);
       lblItemName.setForeground(color);
    }
    public void setValue(Item item)
    {
            if(item!=null)
            {
               lblItemName.setText(item.getItemName());
            }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblItemName = new javax.swing.JLabel();

        lblItemName.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        lblItemName.setForeground(new java.awt.Color(0, 153, 51));
        lblItemName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblItemName, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblItemName, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblItemName;
    // End of variables declaration//GEN-END:variables
}
