/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domesticfinancesystem.regularservice;

import domesticfinancesystem.MainFrame;
import domesticfinancesystem.calendar.Database;
import domesticfinancesystem.regserv.report.RegularServiceReport;
import domesticfinancesystem.shoppinglist.ShoppingListHeader;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Formatter;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author sneha
 */
public class RegularServiceMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegularServiceMainPanel
     */
    private Database dc;
    private Connection con;
    private DefaultListModel<RegularService> regServModel = new DefaultListModel<RegularService>();
    private CalendarPanel cp;
    private SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
    
    public static Date addsubtractDate(Date dt, int days,boolean isAdd)
    {
        GregorianCalendar cal = new GregorianCalendar();
         
        System.out.println("dt = "+dt);
        cal.setTime(dt);
        
        if(isAdd)
            cal.add(Calendar.DATE, days);
        else
           cal.add(Calendar.DATE, -days);
        
        return cal.getTime();
    }
   
    public RegularServiceMainPanel() {
        initComponents();
        dc = MainFrame.dc;
        con = dc.createConnection();
        lstRegularServices.setModel(regServModel);
        lstRegularServices.setCellRenderer(new ListRenderer());
        
        cp = new CalendarPanel(-1, Color.CYAN);
        centralPanel.add(cp);
        
        fetchServiceFromDatabase();
    }
    
    public void addService(RegularService rs)
    {
        regServModel.addElement(rs);
    }
    
    public void updateService(RegularService rs)
    {
        int index = rs.getId();
        for(int i = 0;i<regServModel.size();i++)
            {
                RegularService regServ = regServModel.get(i);
                if(index == regServ.getId())
                {
                   regServModel.removeElementAt(i);
                   break; 
                }
            }
            regServModel.addElement(rs);
            int ind = regServModel.indexOf(rs);
            lstRegularServices.setSelectedIndex(ind);
    }
    
    public void fetchServiceFromDatabase()
    {
        try {
            
            Statement stmt = con.createStatement();
            String sql = "Select Id,Name,RgbVal from ServDef";
            ResultSet rst = stmt.executeQuery(sql);
            while(rst.next())
            {
                int id = rst.getInt("Id");
                String name = rst.getString("Name");
                int rgbVal = rst.getInt("RgbVal");
                RegularService rs = new RegularService(id, name, rgbVal);
                regServModel.addElement(rs);
                lstRegularServices.setSelectedIndex(regServModel.indexOf(rs));
            }
            rst.close();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegularServiceMainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstRegularServices = new javax.swing.JList<>();
        btnCreateService = new javax.swing.JButton();
        btnEditServDef = new javax.swing.JButton();
        centralPanel = new javax.swing.JPanel();
        btnShowServReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(0, 614));

        lstRegularServices.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        lstRegularServices.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstRegularServicesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstRegularServices);

        btnCreateService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testimages/Add.gif"))); // NOI18N
        btnCreateService.setToolTipText("Create New Service");
        btnCreateService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateServiceActionPerformed(evt);
            }
        });

        btnEditServDef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testimages/document_edit.png"))); // NOI18N
        btnEditServDef.setToolTipText("Edit Service Definition");
        btnEditServDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditServDefActionPerformed(evt);
            }
        });

        centralPanel.setLayout(new java.awt.BorderLayout());

        btnShowServReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testimages/report.png"))); // NOI18N
        btnShowServReport.setToolTipText("Show Service Report");
        btnShowServReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowServReportActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel1.setText("Regular Services");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testimages/reg serv.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addComponent(centralPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCreateService)
                        .addGap(34, 34, 34)
                        .addComponent(btnEditServDef)
                        .addGap(29, 29, 29)
                        .addComponent(btnShowServReport, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(138, 138, 138))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEditServDef)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(centralPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(btnCreateService, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnShowServReport, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(69, 69, 69))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateServiceActionPerformed
        // TODO add your handling code here:
        JFrame f = null;
        JDialog dlg= new JDialog(f,true);
        ServiceDefinitionPanel sdp = new ServiceDefinitionPanel(this,dlg);
        if(sdp!=null)
        {
            dlg.add(sdp);
            dlg.pack();
            dlg.setLocationRelativeTo(null);
            dlg.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dlg.setVisible(true);
        }
    }//GEN-LAST:event_btnCreateServiceActionPerformed

    private void btnEditServDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditServDefActionPerformed
        // TODO add your handling code here:
        if(lstRegularServices.getSelectedIndex()>=0)
        {
            RegularService rs = lstRegularServices.getSelectedValue();
            JFrame f = null;
            JDialog dlg= new JDialog(f,true);
            ServiceDefinitionPanel sdp = new ServiceDefinitionPanel(this,dlg,rs.getId());
            if(sdp!=null)
            {
                dlg.add(sdp);
                dlg.pack();
                dlg.setLocationRelativeTo(null);
                dlg.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                dlg.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnEditServDefActionPerformed

    private void lstRegularServicesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstRegularServicesValueChanged
        // TODO add your handling code here:
        if(lstRegularServices.getSelectedIndex()>=0)
        {
            RegularService rs = lstRegularServices.getSelectedValue();
            cp.setIdColor(rs.getId(), new Color(rs.getRgbVal()));
        }
    }//GEN-LAST:event_lstRegularServicesValueChanged

    private void btnShowServReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowServReportActionPerformed
        // TODO add your handling code here:
         if(lstRegularServices.getSelectedIndex()>=0)
        {
            int regservId = lstRegularServices.getSelectedValue().getId();
            JFrame f = null;
            JDialog dlg= new JDialog(f,true);
            RegularServiceReport rsr = new RegularServiceReport(regservId);
            if(rsr!=null)
            {
                dlg.add(rsr);
                dlg.setTitle("Regular Service Report");
                dlg.pack();
                dlg.setLocationRelativeTo(null);
                dlg.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                dlg.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnShowServReportActionPerformed
    private static int noOfDays(Date startDate, Date endDate)
    {
        return (int)(Math.ceil((endDate.getTime() - startDate.getTime())/(double)(24 * 3600 * 1000)));
    }
    public  static boolean extractFreqData(Date startdate,int n,Date dt)//dt is passed dt
    {
        int freqType  = (n)>>>30;
        
        int mask = 0b00_111111_11111111_11111111_11111111 ; //to reset leftmost two bits of n
        n = n & mask;                      //resetting leftmost two bits of n

        if(freqType == 0)
        {
            if(n!=0)
            {
                if(n == 1)
                    return true;
                else if((noOfDays(startdate, dt) == 0))
                    return true;
                else if(noOfDays(startdate, dt)%n == 0)
                    return true;
                else
                    return false;
            }
            else
                return false;
        }
        else if(freqType == 1)
        {
            
            mask = 0b10000000 ; // 0x80 
            int dayOfWeek = dt.getDay();
            
             mask >>>= dayOfWeek ;
            
                 if((n & mask) != 0)   // Corresponding bit is set
                    return true;
                 else
                     return false;
        }
        else if(freqType == 2)
        {
            mask = 0b00_100000_00000000_00000000_00000000 ;
            int day = dt.getDate();
            mask >>>= day;
                 if((n & mask) != 0)   // Corresponding bit is set
                     return true;
                 else
                    return false;
        }
        else
        {
            if(dt.getDate() == 1)
            {
               mask = 0b10000000;     // ox80
               if( (n & mask)!= 0)
                   return true;
            }
            
            if(dt.getDate() == 30)
            {
               mask = 0b01000000;
               if( (n & mask)!= 0)
                   return true;
            }
           
           if(dt.getDate() == 15)
            {
               mask = 0b00100000;
               if( (n & mask)!= 0)
                   return true;
            }
           return false;
        }
    }
    
    @Override  
     public void removeNotify(){  
        MainFrame.startRegServTimer();
        
    }       

    private void formWindowClosing(java.awt.event.WindowEvent evt) {
    }
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RegularServiceMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RegularServiceMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RegularServiceMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RegularServiceMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                JFrame  f = new JFrame();
                
                f.setTitle("Regular Service");
                f.add(new RegularServiceMainPanel());
                f.pack();
                f.setLocationRelativeTo(null);
                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                f.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateService;
    private javax.swing.JButton btnEditServDef;
    private javax.swing.JButton btnShowServReport;
    private javax.swing.JPanel centralPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<RegularService> lstRegularServices;
    // End of variables declaration//GEN-END:variables
}
