/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domesticfinancesystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author sneha
 */
public class OpeningBalanceDialog extends javax.swing.JDialog {

    /**
     * Creates new form OpeningBalanceDialog
     */
    private Connection con;
    private int openingCashBalance;
    private int openingBankBalance;
    public OpeningBalanceDialog(java.awt.Frame parent, boolean modal,int openingCashBalance,int openingBankBalance,Connection con) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.con = con;
        ((AbstractDocument)txtOpeningBankBalnc.getDocument()).setDocumentFilter(new IntegerDocumentFilter());
        ((AbstractDocument)txtOpeningCashBalnc.getDocument()).setDocumentFilter(new IntegerDocumentFilter());
        this.openingBankBalance = openingBankBalance;
        this.openingCashBalance = openingCashBalance;
        if(openingBankBalance!=0)
        {
            txtOpeningBankBalnc.setEnabled(false);
        }
        if(openingCashBalance!=0)
        {
            txtOpeningCashBalnc.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOpeningBankBalnc = new javax.swing.JLabel();
        txtOpeningBankBalnc = new javax.swing.JTextField();
        lblOpeningCashBalnc = new javax.swing.JLabel();
        txtOpeningCashBalnc = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 102));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblOpeningBankBalnc.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        lblOpeningBankBalnc.setForeground(new java.awt.Color(0, 0, 102));
        lblOpeningBankBalnc.setText("Opening Bank Balance");

        txtOpeningBankBalnc.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        txtOpeningBankBalnc.setForeground(new java.awt.Color(0, 0, 102));

        lblOpeningCashBalnc.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        lblOpeningCashBalnc.setForeground(new java.awt.Color(0, 102, 0));
        lblOpeningCashBalnc.setText("Opening Cash Nalance");

        txtOpeningCashBalnc.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        txtOpeningCashBalnc.setForeground(new java.awt.Color(0, 102, 0));

        btnOK.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        btnOK.setForeground(new java.awt.Color(153, 0, 0));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblOpeningBankBalnc, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(lblOpeningCashBalnc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtOpeningBankBalnc)
                    .addComponent(txtOpeningCashBalnc, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpeningBankBalnc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOpeningBankBalnc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpeningCashBalnc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOpeningCashBalnc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        int openingBankBalance,openingCashBalance;
        openingBankBalance = openingCashBalance = 0;
        String opnBankBalnc = txtOpeningBankBalnc.getText().trim();
        if(opnBankBalnc!=null && !opnBankBalnc.isEmpty())
        {
            openingBankBalance = Integer.parseInt(opnBankBalnc);
        }
        String opnCashBalnc = txtOpeningCashBalnc.getText().trim();
        if(opnCashBalnc!=null && !opnCashBalnc.isEmpty())
        {
            openingCashBalance = Integer.parseInt(opnCashBalnc);
        }
        
        if(openingBankBalance!=0 && openingCashBalance!=0)
        {
            try {
                con.setAutoCommit(false);
                String s = "Update SystemSettings set ";
                if(openingBankBalance!=0 && openingCashBalance!=0)
                    s+="openingbankbalance = ?,openingcashbalance = ?,refliqbalance = ?,refdigitbalance = ?";
                else if(openingBankBalance!=0)
                    s+="openingbankbalance = ?,refdigitbalance = ?";
                else if(openingCashBalance!=0)
                    s+="openingcashbalance = ?,refliqbalance = ?";
                
                PreparedStatement pstmt = con.prepareStatement(s);
                if(openingBankBalance!=0 && openingCashBalance!=0)
                {
                    pstmt.setInt(1, openingBankBalance);
                    pstmt.setInt(2, openingCashBalance);
                    pstmt.setInt(3, openingCashBalance);
                    pstmt.setInt(4, openingBankBalance);
                    MainFrame.sysSettings.setOpeningBankBalance(openingBankBalance);
                    MainFrame.sysSettings.setOpeningCashBalance(openingCashBalance);
                    MainFrame.sysSettings.setRefLiqBalance(openingCashBalance);
                    MainFrame.sysSettings.setRefDigitBalance(openingBankBalance);
                    this.openingBankBalance = openingBankBalance;
                    this.openingCashBalance = openingCashBalance;
                }
                else if(openingBankBalance!=0)
                {
                    pstmt.setInt(1, openingBankBalance);
                    pstmt.setInt(2, openingBankBalance);
                    MainFrame.sysSettings.setOpeningBankBalance(openingBankBalance);
                    MainFrame.sysSettings.setRefDigitBalance(openingBankBalance);
                    this.openingBankBalance = openingBankBalance;

                }
                else if(openingCashBalance!=0)
                {
                    pstmt.setInt(1, openingCashBalance);
                    pstmt.setInt(2, openingCashBalance);
                    MainFrame.sysSettings.setOpeningCashBalance(openingCashBalance);
                    MainFrame.sysSettings.setRefLiqBalance(openingCashBalance);
                   this.openingCashBalance = openingCashBalance;

                }
                pstmt.executeUpdate();
                pstmt.close();
                updateCashAndBankBalance();
                con.commit();
                con.setAutoCommit(true);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(OpeningBalanceDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            if(openingBankBalance == 0)
            {
                JOptionPane.showMessageDialog(this, "Please enter opening bank balance", "Message", JOptionPane.ERROR_MESSAGE);
                txtOpeningBankBalnc.requestFocus();
            }
            else if(openingCashBalance == 0)
            {
                JOptionPane.showMessageDialog(this, "Please enter opening cash balance", "Message", JOptionPane.ERROR_MESSAGE);
                txtOpeningCashBalnc.requestFocus();
            }
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void updateCashAndBankBalance() throws SQLException
    {
        String sql = "Update Wallet set Liquidbal = ? where Name = ?";
        PreparedStatement pstmt = con.prepareStatement(sql);
        pstmt.setInt(1, openingCashBalance);
        pstmt.setString(2, "Cash");
        pstmt.executeUpdate();
        pstmt.close();
        
        sql = "Update Wallet set Digitalbal = ? where Name = ?";
        pstmt = con.prepareStatement(sql);
        pstmt.setInt(1, openingBankBalance);
        pstmt.setString(2, "Bank");
        pstmt.executeUpdate();
        pstmt.close();
        
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       JOptionPane.showMessageDialog(rootPane, "Opening balances must be entered", "Message", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_formWindowClosing
              
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpeningBalanceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpeningBalanceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpeningBalanceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpeningBalanceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OpeningBalanceDialog dialog = new OpeningBalanceDialog(new javax.swing.JFrame(), true,0,0,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel lblOpeningBankBalnc;
    private javax.swing.JLabel lblOpeningCashBalnc;
    private javax.swing.JTextField txtOpeningBankBalnc;
    private javax.swing.JTextField txtOpeningCashBalnc;
    // End of variables declaration//GEN-END:variables
}
