/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domesticfinancesystem.wallet;

import domesticfinancesystem.calendar.Database;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author sneha
 */
public class WalletListCellPanel extends javax.swing.JPanel {

    /**
     * Creates new form WalletListCellPanel
     */
    private File file ;
    private Image defaultImage;
    private ImageIcon defIcon;
    private Color green = new Color(0, 102, 0);
    
     private Image scaleImage(Image img)
    {
        int imageHeight = img.getHeight(null);
        int imageWidth = img.getWidth(null);
        int labelHeight = 82;
        int labelWidth =  90;

                   if(imageHeight>imageWidth)
                   {
                        int newWidth =(int) ((double)labelHeight/imageHeight*imageWidth);
                        img = img.getScaledInstance(newWidth, labelHeight, Image.SCALE_SMOOTH);
                   }
                   else if(imageHeight<imageWidth)
                   {
                      int newHeight =(int) ((double)labelWidth/imageWidth*imageHeight);
                      img = img.getScaledInstance( labelWidth,newHeight, Image.SCALE_SMOOTH); 
                   }
                   else
                   {
                      int newWidth =(int) ((double)labelHeight/imageHeight*imageWidth);
                      img = img.getScaledInstance(newWidth, labelHeight, Image.SCALE_SMOOTH); 
                      
                   } 
                   return img;
    }
    
    public void setRendererBackground(Color color)
    {
       super.setBackground(color);
       lblWalletName.setBackground(color);
    }
    public void setRendererForeground(Color color)
    {
       super.setForeground(color);
       lblWalletName.setForeground(color);
    }
    
    public void setValue(Wallet obj,boolean isSelected)
    {
            if(obj!=null)
            {
                Image img = null;
                img = obj.getImg();
                if(img!=null)
                {
                        img = scaleImage(img);
                        ImageIcon icon = new ImageIcon(img);
                        lblWalletIcon.setIcon(icon);
                }
                else
                {
                    lblWalletIcon.setIcon(defIcon);
                }
                if(isSelected)
                {
                    lblLiqBal.setForeground(Color.WHITE);
                    lblDigBal.setForeground(Color.WHITE);
                }
                else
                {
                    lblLiqBal.setForeground(green);
                    lblDigBal.setForeground(Color.BLUE);
                }
                lblWalletName.setText(obj.getName());
                lblLiqBal.setText(""+obj.getLiqbal());
                lblDigBal.setText(""+obj.getDigbal());
            }
    }
  
    public WalletListCellPanel() {
        initComponents();
        file =  new File("extras/Images/WalletIcon.png");
         try {
            defaultImage = ImageIO.read(file);
            defaultImage = scaleImage(defaultImage);
            defIcon = new ImageIcon(defaultImage);
        } catch (IOException ex) {
            Logger.getLogger(WalletDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWalletIcon = new javax.swing.JLabel();
        lblWalletName = new javax.swing.JLabel();
        lblLiqBal = new javax.swing.JLabel();
        lblDigBal = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lblWalletIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lblWalletName.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N

        lblLiqBal.setBackground(new java.awt.Color(255, 255, 255));
        lblLiqBal.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        lblLiqBal.setForeground(new java.awt.Color(0, 102, 0));
        lblLiqBal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLiqBal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDigBal.setBackground(new java.awt.Color(255, 255, 255));
        lblDigBal.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        lblDigBal.setForeground(new java.awt.Color(0, 0, 153));
        lblDigBal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDigBal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWalletIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWalletName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLiqBal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDigBal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblWalletIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDigBal, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(lblLiqBal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblWalletName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDigBal;
    private javax.swing.JLabel lblLiqBal;
    private javax.swing.JLabel lblWalletIcon;
    private javax.swing.JLabel lblWalletName;
    // End of variables declaration//GEN-END:variables
}
